export const randomQuotes = [
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "If life were predictable it would cease to be life and be without flavor.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Life is a succession of lessons which must be lived to be understood.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
  "The only impossible journey is the one you never begin.",
  "In this life we cannot do great things. We can only do small things with great love.",
  "Only a life lived for others is a life worthwhile.",
  "The purpose of our lives is to be happy.",
  "Life is what happens when you're busy making other plans.",
  "You only live once, but if you do it right, once is enough.",
  "Live in the sunshine, swim the sea, drink the wild air.",
  "Go confidently in the direction of your dreams! Live the life you've imagined.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "May you live all the days of your life.",
  "Life itself is the most wonderful fairy tale.",
  "Do not let making a living prevent you from making a life.",
  "Life is ours to be spent, not to be saved.",
  "Life is a long lesson in humility.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "Love the life you live. Live the life you love.",
  "Life is either a daring adventure or nothing at all.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  "Life is made of ever so many partings welded together.",
  "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma — which is living with the results of other people's thinking.",
  "Life is trying things to see if they work.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
];
